plugins:
  topic_gallery_enabled:
    default: true
    client: false
  topic_gallery_allowed_groups:
    type: group_list
    list_type: compact
    default: "1" # admin group
    allow_any: false
    refresh: true
  topic_gallery_minimum_image_size:
    default: 64
    min: 0
    max: 1000
  topic_gallery_post_menu_button:
    default: true
    client: true
